import os
from openai import OpenAI
from config import CHATGPT_MODEL_NAME, CHATGPT_API_ENV_NAME, CHATGPT_HYPO_PROMPT


def generate_hypothetical_problem(user_query: str) -> str:
    """
    Generates a hypothetical math problem based on the user's query.

    Parameters:
        str: user_query
            The text input from the user describing the kind of math problem they are interested in.

    Returns:
        str:
            A math problem generated by ChatGPT that matches the user's query.
    """
    # Get the API key from environment variable
    api_key = os.environ.get(CHATGPT_API_ENV_NAME)
    if not api_key:
        raise RuntimeError(f"API key not found. Please set the environment variable {CHATGPT_API_ENV_NAME} with your ChatGPT API key.")

    client = OpenAI(api_key=api_key)

    # Create the prompt by replacing the placeholder with the actual user query
    prompt = CHATGPT_HYPO_PROMPT.replace("{user_query}", user_query)

    # Call the ChatGPT API to generate a hypothetical problem
    response = client.chat.completions.create(
        model=CHATGPT_MODEL_NAME,
        messages=[
            {"role": "system", "content": "You are a helpful math teacher."},
            {"role": "user", "content": prompt},
        ],
    )

    # Extract the generated problem from the API response
    content = response.choices[0].message.content
    
    if content is None:
        raise RuntimeError(f"ChatGPT returned empty content: {response}")

    return content.strip()